# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tip',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
