# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
